### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Fernanda-a** [RobTillaart/INA3221_RT#6]
https://github.com/RobTillaart/INA3221_RT/blob/f29bffd44dbf9eacd14555b283be11ac4e13e4be/INA3221.cpp#L165

Isn't it supposed to be setCriticalCurrent instead of setCriticalCurrect?

**Comment by RobTillaart** [comment]
Good catch!
Thanks for reporting, 
labelled as bug to give it some priority

**Comment by RobTillaart** [comment]
@Fernanda-a 
Will update to version 0.3.0 to fix this typo today.
